apiVersion: v1
kind: Service
metadata:
    name: lerna-docker-apps-back-service
spec:
    type: ClusterIP
    ports:
        - targetPort: 4000
          port: 80
    selector:
        app: lerna-docker-apps-back
        type: backend
        environment: production
