apiVersion: apps/v1
kind: Deployment
metadata:
    name: lerna-docker-apps-front-deploy
    labels:
        app: lerna-docker-apps-front
        tier: frontend
spec:
    selector:
        matchLabels:
            app: lerna-docker-apps-front
    template:
        metadata:
            name: lerna-docker-apps-front
            labels:
                app: lerna-docker-apps-front
                type: frontend
                environment: production
        spec:
            containers:
                - name: lerna-docker-apps-front-container
                  image: israelfacanha/lerna-docker-apps-front:latest
                  resources:
                      limits:
                          memory: '128Mi'
                          cpu: '500m'
                  ports:
                      - containerPort: 3000
    replicas: 5
