apiVersion: v1
kind: Pod
metadata:
    name: lerna-docker-apps-front
    labels:
        name: lerna-docker-apps-front
        lib: NextJs
        type: frontend
        environment: production
spec:
    containers:
        - name: lerna-docker-apps-front-container
          image: israelfacanha/lerna-docker-apps-front
          resources:
              limits:
                  memory: '128Mi'
                  cpu: '500m'
          ports:
              - containerPort: 3000
