apiVersion: v1
kind: Service
metadata:
    name: lerna-docker-apps-front-service
spec:
    type: NodePort
    ports:
        - targetPort: 3000
          port: 80
          nodePort: 30000
    selector:
        app: lerna-docker-apps-front
        type: frontend
        environment: production
